# Book settings
title: Software Engineering Capstone
author: Tawnya Lee
logo: images/logo.jpg
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md"]
only_build_toc_files: true

bibtex_bibfiles:
  - about/citations.bib

latex:
  latex_documents:
    targetname: book.tex
html:
  home_page_in_navbar : true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  navbar_number_sections : false
  announcement: "Use this JupyterBook as a <a href='https://github.com/firasm/jupyterbook_course_template' style='color:pink;'>template by clicking here</a>!"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  # google_analytics_id: UA-11111111 # add your Google Analytics Tracking Code
  comments:
    hypothesis: false
    utterances:
      repo: "firasm/jupyterbook_course_template"
    dokieli: false
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>

launch_buttons:
  notebook_interface : "jupyterlab"
  binderhub_url      : "https://mybinder.org"
  thebe              : true

repository: 
  url          : https://github.com/firasm/jupyterbook_course_template
  path_to_book : ""
  branch       : main

sphinx:
  config:
    html_show_copyright: false
    html_extra_path: ['files']
    bibtex_reference_style: author_year
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - substitution

    myst_substitutions:
      INSTRUCTOR: "Tawnya Lee"
      PRONOUNCE: "Ton ya Lee"
      OFFICE: "N/A"
      PHONE: "N/A"
      COURSE_CODE: "D424"
      SECTION: "001"
      CREDITS: "3"
      TITLE: "Software Engineering Capstone"
      PREREQS: "N/A"
      COREQS: "N/A"
      TERM: ""
      ROOM: ""
      MEETING_TIMES: ""
      GRACE_PERIOD: "48 hour"
      W_DATE_1: "11:59 PDT on January 22, 2021"
      W_DATE_2: "11:59 PDT on March 26, 2021"
      W_DATE_3: "11:59 PDT on March 26, 2021"
      EXAM_PERIOD: ""
      CANVAS_ID: "63995"
      CANVAS_LINK: ""
      ZOOM_LINK: ""
      ANNOUNCEMENTS_LINK: ""
      COURSE_LINK: ""
      FORUM_LINK: ""
      ANALYTICS_OPTOUT: ""
      FORMAT: ""
      ASSOCIATE_HEAD: ""
      ANON_FEEDBACK: ""
      TEXTBOOK: "We will not be needing a textbook for this course as you will be provided all the notes you need via the course website."
